"""create hashtag table

Revision ID: 08bdc7c639ba
Revises: 15fbc23b8cb6
Create Date: 2025-08-03 19:45:41.004853

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bdc7c639ba'
down_revision: Union[str, Sequence[str], None] = '15fbc23b8cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('week_posts', sa.Integer(), nullable=True),
    sa.Column('total_posts', sa.BigInteger(), nullable=True),
    sa.Column('view_weight', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashtag')
    )
    op.create_index(op.f('ix_hashtags_id'), 'hashtags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hashtags_id'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
