"""Add embedding column to youtube_videos

Revision ID: 15fbc23b8cb6
Revises: 13b5fda19037
Create Date: 2025-07-30 19:22:35.179363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '15fbc23b8cb6'
down_revision: Union[str, Sequence[str], None] = '13b5fda19037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_videos', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'embedding')
    # ### end Alembic commands ###
