"""Add is_active column to hashtag table

Revision ID: 351305147a7d
Revises: f103b8839c7c
Create Date: 2025-10-31 01:52:04.057257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351305147a7d'
down_revision: Union[str, Sequence[str], None] = 'f103b8839c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 컬럼 추가와 동시에 기존 행에 True 값 부여 (server_default=sa.text('true')로 처리)
    op.add_column('hashtags', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # 2. DEFAULT 제약 조건 제거 (클린업)
    op.alter_column('hashtags', 'is_active', server_default=None, existing_type=sa.Boolean())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashtags', 'is_active')
    # ### end Alembic commands ###
