"""create hashtag_history, video_feedback table

Revision ID: 49c90ba929c0
Revises: 8d9e80dd5553
Create Date: 2025-08-26 16:24:41.862075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c90ba929c0'
down_revision: Union[str, Sequence[str], None] = '8d9e80dd5553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hashtag', sa.String(), nullable=False),
    sa.Column('week_posts', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtag_history_id'), 'hashtag_history', ['id'], unique=False)
    op.create_table('video_feedback',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('similar_videos', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_feedback')
    op.drop_index(op.f('ix_hashtag_history_id'), table_name='hashtag_history')
    op.drop_table('hashtag_history')
    # ### end Alembic commands ###
