"""Create content_feedback table and modify many tables

Revision ID: 8929a2817c5d
Revises: 351305147a7d
Create Date: 2025-11-02 17:55:28.350872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8929a2817c5d'
down_revision: Union[str, Sequence[str], None] = '351305147a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_feedback',
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.String(), nullable=True),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('similar_videos', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_content_feedback_feedback_id'), 'content_feedback', ['feedback_id'], unique=False)
    op.drop_table('video_feedback')

    op.add_column('keywords', sa.Column('feedback_id', sa.Integer(), nullable=False))

    op.drop_constraint(op.f('keywords_video_id_fkey'), 'keywords', type_='foreignkey')
    op.create_foreign_key(None, 'keywords', 'content_feedback', ['feedback_id'], ['feedback_id'], ondelete='CASCADE')
    op.drop_column('keywords', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'keywords', type_='foreignkey')
    op.create_foreign_key(op.f('keywords_video_id_fkey'), 'keywords', 'videos', ['video_id'], ['video_id'], ondelete='CASCADE')
    op.drop_column('keywords', 'feedback_id')
    op.create_table('video_feedback',
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titles', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hashtags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('similar_videos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], name=op.f('video_feedback_video_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', name=op.f('video_feedback_pkey'))
    )
    op.drop_index(op.f('ix_content_feedback_feedback_id'), table_name='content_feedback')
    op.drop_table('content_feedback')
    # ### end Alembic commands ###
