"""add view_count column to youtube_videos table

Revision ID: f103b8839c7c
Revises: 49c90ba929c0
Create Date: 2025-08-28 15:37:33.221495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f103b8839c7c'
down_revision: Union[str, Sequence[str], None] = '49c90ba929c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_videos', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('youtube_videos', 'view_count')
    # ### end Alembic commands ###
