"""update user table structure

Revision ID: 9220d24234c3
Revises: c8a0ef3c167b
Create Date: 2025-07-14 12:02:58.339879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9220d24234c3'
down_revision: Union[str, Sequence[str], None] = 'c8a0ef3c167b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_provider', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('user_social_id', sa.String(length=255), nullable=True))
    op.drop_index(op.f('user_kakao_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users')
    op.create_index(op.f('ix_users_user_nickname'), 'users', ['user_nickname'], unique=False)
    op.create_unique_constraint('uix_social_provider', 'users', ['user_social_id', 'user_provider'])
    op.create_unique_constraint(None, 'users', ['user_social_id'])
    op.drop_column('users', 'user_kakao_id')
    op.drop_column('users', 'user_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('users', sa.Column('user_kakao_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uix_social_provider', 'users', type_='unique')
    op.drop_index(op.f('ix_users_user_nickname'), table_name='users')
    op.create_index(op.f('ix_users_user_nickname'), 'users', ['user_nickname'], unique=True)
    op.create_index(op.f('user_kakao_id'), 'users', ['user_kakao_id'], unique=True)
    op.drop_column('users', 'user_social_id')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'user_provider')
    # ### end Alembic commands ###
